version: '3.8'
services:
  site:
    image: registry.gitlab.com/oneentry-skd-js/nextjs-shop:latest
    container_name: nextjs-shop
    restart: unless-stopped
    networks:
      - nextjs-shop
    ports:
      - '3009:3000'

networks:
  nextjs-shop:
    name: nextjs-shop
    driver: bridge
