import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';

import Footer from '../components/layout/Footer';
import Header from '../components/layout/Header';
import NavigationMenu from '../components/layout/navbar/NavigationMenu';
import { AuthProvider } from './store/providers/AuthContext';
import { ContentContextProvider } from './store/providers/ContentContext';
import { LanguageProvider } from './store/providers/LanguageContext';
import { OpenDrawerProvider } from './store/providers/OpenDrawerContext';
import StoreProvider from './store/providers/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OneEntry Shop',
  description: 'OneEntry next-js shop',
};

const navigationItems = [
  {
    label: 'Category',
    href: '/',
    hasDropdown: true,
  },
  {
    label: 'Promotion',
    href: '/promotion',
  },
  {
    label: 'New arrival',
    href: '/arrival',
  },
  {
    label: 'BEST SELLERS',
    href: '/best-sellers',
  },
  {
    label: 'OFFER OF TODAY',
    href: '/offers',
  },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon" />
      </Head>
      <body className={inter.className}>
        <StoreProvider>
          <LanguageProvider>
            <AuthProvider>
              <ContentContextProvider>
                <OpenDrawerProvider>
                  <Header />
                  <NavigationMenu items={navigationItems} />
                  {children}
                  <Footer />
                </OpenDrawerProvider>
              </ContentContextProvider>
            </AuthProvider>
          </LanguageProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
