export const navigationItems = [
  {
    label: 'Category',
    href: '#',
    hasDropdown: true,
    submenu: [
      {
        label: 'New arrival',
        href: '/arrival',
      },
      {
        label: 'BEST SELLERS',
        href: '/best-sellers',
      },
      {
        label: 'OFFER OF TODAY',
        href: '/offers',
      },
    ],
  },
  {
    label: 'Promotion',
    href: '/promotion',
  },
  {
    label: 'New arrival',
    href: '/arrival',
  },
  {
    label: 'BEST SELLERS',
    href: '/best-sellers',
  },
  {
    label: 'OFFER OF TODAY',
    href: '/offers',
  },
];

export const productsGroup = [
  {
    id: 82,
    localizeInfos: { title: 'Set (2 items) 2 Dolls' },
    statusIdentifier: 'in_stock',
    statusLocalizeInfos: { title: 'In stock' },
    attributeSetIdentifier: 'product',
    position: 1,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 67,
    additional: { prices: { min: 10, max: 299 } },
    sku: 'SO0103',
    isSync: true,
    attributeValues: {
      pic: {
        type: 'image',
        value: {
          downloadLink: '/images/catalog-img-2.svg',
        },
        position: 2,
        isProductPreview: true,
      },
      sku: {
        type: 'string',
        value: 'SO0103',
        position: 8,
        isProductPreview: false,
      },
      sale: {
        type: 'integer',
        value: '',
        position: 4,
        isProductPreview: false,
      },
      color: {
        type: 'list',
        value: {},
        position: 5,
        isProductPreview: false,
      },
      price: {
        type: 'integer',
        value: '67',
        position: 1,
        isProductPreview: false,
      },
      category: {
        type: 'list',
        value: {},
        position: 7,
        isProductPreview: false,
      },
      currency: {
        type: 'string',
        value: 'USD',
        position: 10,
        isProductPreview: false,
      },
      more_pic: {
        type: 'groupOfImages',
        value: {},
        position: 3,
        isProductPreview: false,
      },
      stickers: {
        type: 'list',
        value: {},
        position: 6,
        isProductPreview: false,
      },
      description: {
        type: 'text',
        value: {},
        position: 0,
        isProductPreview: false,
      },
      units_product: {
        type: 'integer',
        value: '4',
        position: 9,
        isProductPreview: false,
      },
    },
    isVisible: true,
    productPages: { id: 260, pageId: 5, productId: 82, positionId: 3453 },
    blocks: [],
  },
  {
    id: 83,
    localizeInfos: { title: 'Set (3 items) 2 Dolls' },
    statusIdentifier: 'in_stock',
    statusLocalizeInfos: { title: 'In stock' },
    attributeSetIdentifier: 'product',
    position: 1,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 167,
    additional: { prices: { min: 10, max: 299 } },
    sku: 'SO0103',
    isSync: true,
    attributeValues: {
      pic: {
        type: 'image',
        value: {
          downloadLink: '/images/catalog-img-3.svg',
        },
        position: 2,
        isProductPreview: true,
      },
      sku: {
        type: 'string',
        value: 'SO0103',
        position: 8,
        isProductPreview: false,
      },
      sale: {
        type: 'integer',
        value: '',
        position: 4,
        isProductPreview: false,
      },
      color: {
        type: 'list',
        value: {},
        position: 5,
        isProductPreview: false,
      },
      price: {
        type: 'integer',
        value: '67',
        position: 1,
        isProductPreview: false,
      },
      category: {
        type: 'list',
        value: {},
        position: 7,
        isProductPreview: false,
      },
      currency: {
        type: 'string',
        value: 'USD',
        position: 10,
        isProductPreview: false,
      },
      more_pic: {
        type: 'groupOfImages',
        value: {},
        position: 3,
        isProductPreview: false,
      },
      stickers: {
        type: 'list',
        value: {},
        position: 6,
        isProductPreview: false,
      },
      description: {
        type: 'text',
        value: {},
        position: 0,
        isProductPreview: false,
      },
      units_product: {
        type: 'integer',
        value: '4',
        position: 9,
        isProductPreview: false,
      },
    },
    isVisible: true,
    productPages: { id: 260, pageId: 5, productId: 82, positionId: 3453 },
    blocks: [],
  },
  {
    id: 84,
    localizeInfos: { title: 'Set (6 items) 3 Dolls' },
    statusIdentifier: 'in_stock',
    statusLocalizeInfos: { title: 'In stock' },
    attributeSetIdentifier: 'product',
    position: 1,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 167,
    additional: { prices: { min: 10, max: 299 } },
    sku: 'SO0103',
    isSync: true,
    attributeValues: {
      pic: {
        type: 'image',
        value: {
          downloadLink: '/images/catalog-img-4.svg',
        },
        position: 2,
        isProductPreview: true,
      },
      sku: {
        type: 'string',
        value: 'SO0103',
        position: 8,
        isProductPreview: false,
      },
      sale: {
        type: 'integer',
        value: '',
        position: 4,
        isProductPreview: false,
      },
      color: {
        type: 'list',
        value: {},
        position: 5,
        isProductPreview: false,
      },
      price: {
        type: 'integer',
        value: '67',
        position: 1,
        isProductPreview: false,
      },
      category: {
        type: 'list',
        value: {},
        position: 7,
        isProductPreview: false,
      },
      currency: {
        type: 'string',
        value: 'USD',
        position: 10,
        isProductPreview: false,
      },
      more_pic: {
        type: 'groupOfImages',
        value: {},
        position: 3,
        isProductPreview: false,
      },
      stickers: {
        type: 'list',
        value: {},
        position: 6,
        isProductPreview: false,
      },
      description: {
        type: 'text',
        value: {},
        position: 0,
        isProductPreview: false,
      },
      units_product: {
        type: 'integer',
        value: '4',
        position: 9,
        isProductPreview: false,
      },
    },
    isVisible: true,
    productPages: { id: 260, pageId: 5, productId: 82, positionId: 3453 },
    blocks: [],
  },
];

export const pages = [
  {
    id: 8,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'home',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'Home',
      content: '',
      menuTitle: 'Home',
      htmlContent: '',
      plainContent: '',
    },
    position: 1,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'order_details',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 5,
    config: { rowsPerPage: 1, productsPerRow: 2 },
    depth: 0,
    parentId: null,
    pageUrl: 'shop',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'Shop',
      content: '',
      menuTitle: 'Shop',
      htmlContent: '',
      plainContent: 'Hello world',
    },
    position: 2,
    isVisible: true,
    products: 9,
    childrenCount: 9,
    type: 'forCatalogPages',
    templateIdentifier: 'shop',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 18,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: '404',
    attributeSetIdentifier: 'Error',
    localizeInfos: {
      title: '404',
      content: '',
      menuTitle: '404',
      htmlContent:
        '<p><img src="https://react-native-course.oneentry.cloud/cloud-static/files/project/page/18/editor/Frame-2-1697392091740.png" width="300px"></p>',
      plainContent: '',
    },
    position: 3,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forErrorPage',
    templateIdentifier: null,
    isSync: true,
    attributeValues: { error_title: [Object], error_description: [Object] },
  },
  {
    id: 25,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'profile',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'Profile',
      menuTitle: 'Profile',
      htmlContent: '<p><br></p>',
      plainContent: '',
    },
    position: 4,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'profile',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 26,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'favorites',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'Favorites',
      menuTitle: 'Favorites',
      htmlContent: '',
      plainContent: '',
    },
    position: 5,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'favorites',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 27,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'cart',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'Cart',
      menuTitle: 'Cart',
      htmlContent: '',
      plainContent: '',
    },
    position: 6,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'cart',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 28,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'orders',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'My orders',
      menuTitle: 'My orders',
      htmlContent: '',
      plainContent: '',
    },
    position: 7,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'orders',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 31,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'contact_us',
    attributeSetIdentifier: 'menu_page',
    localizeInfos: {
      title: 'Contact us',
      menuTitle: 'Contact us',
      htmlContent: '',
      plainContent: '',
    },
    position: 8,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'contact_us',
    isSync: true,
    attributeValues: {
      icon: [Object],
      home_title: [Object],
      show_title: [Object],
    },
  },
  {
    id: 32,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'place_an_order',
    attributeSetIdentifier: 'page',
    localizeInfos: {
      title: 'Place an order',
      menuTitle: 'Place an order',
      htmlContent: '',
      plainContent: '',
    },
    position: 9,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'place_an_order',
    isSync: true,
    attributeValues: { show_title: [Object] },
  },
  {
    id: 33,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'product',
    attributeSetIdentifier: null,
    localizeInfos: {
      title: 'Product',
      menuTitle: 'Product',
      htmlContent: '',
      plainContent: '',
    },
    position: 10,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: null,
    isSync: false,
    attributeValues: {},
  },
  {
    id: 35,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'about_us',
    attributeSetIdentifier: 'about_page',
    localizeInfos: {
      title: 'About us',
      menuTitle: 'About us',
      htmlContent: '',
      plainContent: '',
    },
    position: 11,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: null,
    isSync: true,
    attributeValues: { img: [Object], about_content: [Object] },
  },
  {
    id: 36,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'catalog_filters',
    attributeSetIdentifier: 'filters',
    localizeInfos: {
      title: 'Catalog Filters',
      menuTitle: 'Catalog Filters',
      htmlContent: '',
      plainContent: '',
    },
    position: 12,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: null,
    isSync: true,
    attributeValues: {
      color_filter: [Object],
      price_filter: [Object],
      availability_filter: [Object],
    },
  },
  {
    id: 38,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'payment',
    attributeSetIdentifier: 'page',
    localizeInfos: {
      title: 'Payment',
      menuTitle: 'Payment',
      htmlContent: '',
      plainContent: '',
    },
    position: 13,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'payment',
    isSync: true,
    attributeValues: { show_title: [Object] },
  },
  {
    id: 39,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'payment_success',
    attributeSetIdentifier: 'page',
    localizeInfos: {
      title: 'Successful payment',
      menuTitle: 'Successful payment',
      htmlContent: '',
      plainContent: '',
    },
    position: 14,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'payment_success',
    isSync: true,
    attributeValues: { show_title: [Object] },
  },
  {
    id: 40,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'payment_canceled',
    attributeSetIdentifier: 'page',
    localizeInfos: {
      title: 'Canceled payment',
      menuTitle: 'Canceled payment',
      htmlContent: '',
      plainContent: '',
    },
    position: 15,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'payment_canceled',
    isSync: true,
    attributeValues: { show_title: [Object] },
  },
  {
    id: 41,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'order_details',
    attributeSetIdentifier: 'page',
    localizeInfos: {
      title: 'Order details',
      menuTitle: 'Order details',
      htmlContent: '',
      plainContent: '',
    },
    position: 16,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'order_details',
    isSync: true,
    attributeValues: { show_title: [Object] },
  },
  {
    id: 42,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'services',
    attributeSetIdentifier: null,
    localizeInfos: {
      title: 'Services',
      menuTitle: 'Services',
      htmlContent: '',
      plainContent: '',
    },
    position: 17,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forCatalogPages',
    templateIdentifier: null,
    isSync: false,
    attributeValues: {},
  },
  {
    id: 43,
    config: {},
    depth: 0,
    parentId: null,
    pageUrl: 'home_web',
    attributeSetIdentifier: 'page',
    localizeInfos: {
      title: 'Home web',
      content: '',
      menuTitle: 'Home web',
      htmlContent: '',
      plainContent: '',
    },
    position: 18,
    isVisible: true,
    products: 0,
    childrenCount: 0,
    type: 'forUsualPage',
    templateIdentifier: 'home',
    isSync: true,
    attributeValues: { show_title: [Object] },
  },
];

export const userMenuItems = [
  {
    icon: '/icons/user.svg',
    text: 'My Profile',
    href: '/profile',
  },
  {
    icon: '/icons/orders.svg',
    text: 'My Orders',
    href: '/orders',
  },
  {
    icon: '/icons/cart.svg',
    text: 'Cart',
    href: '/cart',
  },
  {
    icon: '/icons/orders.svg',
    text: 'Payments',
    href: '/payments',
  },
  {
    icon: '/icons/heart.svg',
    text: 'Favorites',
    href: '/favorites',
  },
];

export const catalogCards = [
  {
    title: 'Catalog',
    backgroundColor: 'bg-amber-600',
    width: 'w-full',
    height: 'h-[175px]',
    imageSrc: '/images/catalog-img-1.svg',
    link: '/catalog',
  },
  {
    title: 'BEST SELLER',
    backgroundColor: 'bg-purple-600',
    width: 'w-full lg:w-[calc(_33%_-_0.65rem)] md:w-[calc(_50%_-_0.65rem)]',
    height: 'h-[260px]',
    imageSrc: '/images/catalog-img-2.svg',
    link: '',
  },
  {
    title: 'PROMOTION',
    backgroundColor: 'bg-blue-500',
    width: 'w-full lg:w-[calc(_33%_-_0.65rem)] md:w-[calc(_50%_-_0.65rem)]',
    height: 'h-[260px]',
    imageSrc: '/images/catalog-img-3.svg',
    link: '',
  },
  {
    title: 'OFFER OF TODAY',
    backgroundColor: 'bg-lime-700',
    width: 'w-full lg:w-[calc(_33%_-_0.65rem)] md:w-[calc(_50%_-_0.65rem)]',
    height: 'h-[260px]',
    imageSrc: '/images/catalog-img-4.svg',
    link: '',
  },
  {
    title: 'NEW\nARRIVALS',
    backgroundColor: 'bg-teal-300',
    width: 'w-full md:w-[calc(_50%_-_0.65rem)]',
    height: 'h-[260px]',
    imageSrc: '/images/catalog-img-5.svg',
    link: '',
  },
  {
    title: 'Join OUR COMMUNITY',
    backgroundColor: 'bg-amber-300',
    width: 'w-full lg:w-[calc(_50%_-_0.65rem)]',
    height: 'h-[260px]',
    imageSrc: '/images/catalog-img-6.svg',
    link: '',
  },
];

export const menuItems = [
  {
    icon: '/icons/user.svg',
    href: '/profile',
    title: 'user',
  },
  {
    icon: '/icons/heart.svg',
    href: '/favorites',
    title: 'heart',
  },
  {
    icon: '/icons/cart.svg',
    href: '/cart',
    title: 'cart',
  },
];

export const productsInCart = [
  {
    id: 80,
    imageSrc: '',
    productName: 'productName',
    price: 1250,
    count: 1,
  },
  {
    id: 1245,
    imageSrc: '',
    productName: 'product Name 2',
    price: 2250,
    count: 3,
  },
];
