import type { PayloadAction, WritableDraft } from '@reduxjs/toolkit'; // Importing the PayloadAction type from Redux Toolkit for type-safe actions.
import { createSlice } from '@reduxjs/toolkit'; // Importing the createSlice function from Redux Toolkit to create a slice of the Redux state.

import type { FavLedger } from '@/app/store/utils/ledger';
import { favActiveIds } from '@/app/store/utils/ledger';

/**
 * The initial state for the favorites slice.
 * @property {number[]}  products - An array of product IDs representing favorite items.
 * @property {FavLedger} meta     - Tombstone ledger (id → last add/remove) used to merge with the server without resurrecting deletions.
 * @property {number}    version  - A version number to track changes in the favorites list.
 */
type InitialStateType = {
  products: number[]; // An array of product IDs representing favorite items.
  meta: FavLedger; // Tombstone ledger keyed by product id.
  version: number; // A version number to track changes in the favorites list.
};

/**
 * Define the initial state for the favorites slice.
 * @property {Array}     products - An array of product IDs representing favorite items.
 * @property {FavLedger} meta     - Tombstone ledger (empty by default).
 * @property {number}    version  - A version number to track changes in the favorites list.
 */
const initialState: InitialStateType = {
  products: [],
  meta: {},
  version: 0,
};

/**
 * Create a slice for managing favorite products.
 * @param name         - Name of the slice.
 * @param initialState - The initial state for the slice.
 * @param reducers     - An object containing the reducer functions for managing the favorites slice.
 */
export const favoritesSlice = createSlice({
  name: 'favorites-slice',
  initialState,
  reducers: {
    /**
     * Add a product to the favorites list and record the add in the ledger.
     * The timestamp is injected by the `prepare` callback so the reducer stays
     * pure while still enabling last-write-wins merges with the server.
     */
    addFavorites: {
      reducer(
        state: WritableDraft<InitialStateType>,
        action: PayloadAction<{ id: number; ts: number }>,
      ) {
        const { id, ts } = action.payload;
        /** Add to the active list only if it is not already there. */
        if (!state.products.includes(id)) {
          state.products.push(id);
        }
        /** Record the add — overrides any previous tombstone for this id. */
        state.meta[id] = { ts, removed: false };
      },
      prepare(id: number) {
        return { payload: { id, ts: Date.now() } };
      },
    },
    /**
     * Remove a product from the favorites list and leave a tombstone in the
     * ledger so the deletion survives a later merge with the server.
     */
    removeFavorites: {
      reducer(
        state: WritableDraft<InitialStateType>,
        action: PayloadAction<{ id: number; ts: number }>,
      ) {
        const { id, ts } = action.payload;
        state.products = state.products.filter((product) => product !== id);
        /** Tombstone: keep the id with `removed: true` and the removal time. */
        state.meta[id] = { ts, removed: true };
      },
      prepare(id: number) {
        return { payload: { id, ts: Date.now() } };
      },
    },
    /**
     * Remove all products from the favorites list, tombstoning each one so the
     * clear is propagated to the server instead of being ignored.
     */
    removeAllFavorites: {
      reducer(
        state: WritableDraft<InitialStateType>,
        action: PayloadAction<{ ts: number }>,
      ) {
        const { ts } = action.payload;
        for (const id of state.products) {
          state.meta[id] = { ts, removed: true };
        }
        state.products = [];
      },
      prepare() {
        return { payload: { ts: Date.now() } };
      },
    },
    /**
     * Replace the ledger with a merged one (server + local) and recompute the
     * active list from it. Dispatched once per session after authentication.
     * @param {WritableDraft<InitialStateType>} state  - Current state
     * @param {PayloadAction<FavLedger>}        action - Payload with the merged ledger
     */
    mergeFavorites(
      state: WritableDraft<InitialStateType>,
      action: PayloadAction<FavLedger>,
    ) {
      state.meta = action.payload;
      state.products = favActiveIds(action.payload);
    },
    /**
     * Set the version of the favorites list.
     * @param {WritableDraft<InitialStateType>} state  - Current state
     * @param {PayloadAction<number>}           action - Payload with version number
     */
    setFavoritesVersion(
      state: WritableDraft<InitialStateType>,
      action: PayloadAction<number>,
    ) {
      state.version = action.payload; // Update the version number.
    },
  },
});

/** Export the actions generated by createSlice for use in dispatching. */
export const {
  addFavorites,
  removeFavorites,
  removeAllFavorites,
  mergeFavorites,
  setFavoritesVersion,
} = favoritesSlice.actions;

/**
 * Selector to get the list of favorite product IDs.
 * @param   {object}   state                           - The global state object.
 * @param   {object}   state.favoritesReducer          - The favorites reducer slice.
 * @param   {number[]} state.favoritesReducer.products - The array of product IDs that are marked as favorites.
 * @returns {number}                                   An array of product IDs that are marked as favorites.
 */
export const selectFavoritesItems = (state: {
  favoritesReducer: { products: number[] };
}): number[] => state.favoritesReducer.products;

/**
 * Selector to get the favorites tombstone ledger.
 * @param   {object}    state                       - The global state object.
 * @param   {object}    state.favoritesReducer      - The favorites reducer slice.
 * @param   {FavLedger} state.favoritesReducer.meta - The favorites ledger.
 * @returns {FavLedger}                             The favorites tombstone ledger.
 */
export const selectFavoritesMeta = (state: {
  favoritesReducer: { meta: FavLedger };
}): FavLedger => state.favoritesReducer.meta;

/**
 * Selector to check if a specific product ID is in the favorites list.
 * @param   {object}   state                           - The global state object.
 * @param   {object}   state.favoritesReducer          - The favorites reducer slice.
 * @param   {number[]} state.favoritesReducer.products - The array of product IDs that are marked as favorites.
 * @param   {number}   id                              - The product ID to check.
 * @returns {boolean}                                  A boolean indicating whether the product ID is in the favorites list.
 */
export const selectIsFavorites = (
  state: { favoritesReducer: { products: number[] } },
  id: number,
): boolean => {
  const added = state.favoritesReducer.products.findIndex(
    (product: number) => product === id,
  );
  return added !== -1; // Return true if the product ID is found, false otherwise.
};

/**
 * Selector to get the current version of the favorites list.
 * @param   {object} state                          - The global state object.
 * @param   {object} state.favoritesReducer         - The favorites reducer slice.
 * @param   {number} state.favoritesReducer.version - The version number of the favorites list.
 * @returns {number}                                The version number of the favorites list.
 */
export const selectFavoritesVersion = (state: {
  favoritesReducer: { version: number };
}): number => state.favoritesReducer.version;

/** Export the be used in the store configuration. */
export default favoritesSlice.reducer;
