import type { PayloadAction } from '@reduxjs/toolkit';
import { createSlice } from '@reduxjs/toolkit';
import type {
  IOrderProductData,
  IOrdersFormData,
} from 'oneentry/dist/orders/ordersInterfaces';

/**
 * Defining the application-specific order type.
 *
 * @property formIdentifier - Optional identifier for the form.
 * @property paymentAccountIdentifier - Optional identifier for the payment account.
 * @property formData - Array of form data with an optional validity flag.
 * @property products - Array of order product data.
 */
export type IAppOrder = {
  formIdentifier?: string;
  paymentAccountIdentifier?: string;
  formData: Array<IOrdersFormData & { valid?: boolean }>;
  products: Array<IOrderProductData>;
};

/**
 * Defining the shape of the initial state for the order slice.
 *
 * @property order - The current order.
 * @property currency - Optional currency type for the order.
 * @property paymentMethods - Optional array of payment methods.
 */
type InitialStateType = {
  order: IAppOrder;
  currency?: string;
  paymentMethods?: Array<{
    identifier: string;
  }>;
};

/**
 * Initial state for the order slice.
 *
 * @property {IAppOrder} order - The current order.
 * @property {Array} order.formData - Array of form data.
 * @property {Array} order.products - Array of products.
 */
const initialState: InitialStateType = {
  order: {
    formData: [],
    products: [],
  },
};

/**
 * Creating a Redux slice for order management.
 *
 * @param name - Name of the slice.
 * @param initialState - The initial state for the slice.
 * @param reducers - An object containing the reducer functions for managing the favorites slice.
 */
const orderReducer = createSlice({
  name: 'order',
  initialState,
  reducers: {
    /**
     * Create or update an order.
     *
     * @param state - Current state.
     * @param action - Payload with order data.
     */
    create(state, action: PayloadAction<IAppOrder>) {
      if (!state.order) {
        // If no order exists, set the new order
        state.order = action.payload;
      } else {
        // Merge the new order data with the existing order
        state.order = {
          ...action.payload,
          ...state.order,
        };
      }
    },
    /**
     * Remove an order by resetting it to its initial state.
     *
     * @param state - Current state.
     */
    remove(state) {
      state.order = {
        formData: [], // Reset form data
        products: [], // Reset products
      };
    },
    /**
     * Add or update form data in the order.
     *
     * @param state - Current state.
     * @param action - Payload with form data.
     */
    addData(
      state,
      action: PayloadAction<IOrdersFormData & { valid?: boolean }>,
    ) {
      if (!state.order) {
        // If no order exists, do nothing
        return;
      }
      const ind = state.order.formData.findIndex(
        (item) => item.marker === action.payload.marker,
      );

      if (ind !== -1) {
        // Update existing form data
        state.order.formData[ind] = action.payload;
      } else {
        // Add new form data
        state.order.formData.push(action.payload);
      }
    },
    /**
     * Add products to the order
     *
     * @param state - Current state
     * @param action - Payload with array of products
     */
    addProducts(state, action: PayloadAction<IOrderProductData[]>) {
      if (!state.order) {
        // If no order exists, do nothing
        return;
      }
      // Set the products in the order
      state.order.products = action.payload;
    },
    /**
     * Add payment methods to the order
     *
     * @param state - Current state
     * @param action - Payload with array of payment methods
     */
    addPaymentMethods(
      state,
      action: PayloadAction<
        Array<{
          identifier: string;
        }>
      >,
    ) {
      if (!state.paymentMethods) {
        // Set the payment methods if they don't exist
        state.paymentMethods = action.payload;
      }
    },
    /**
     * Set the payment account identifier for the order
     *
     * @param state - Current state
     * @param action - Payload with payment method identifier
     */
    addPaymentMethod(state, action: PayloadAction<string>) {
      if (!state.order) {
        // If no order exists, do nothing
        return;
      }
      // Set the payment account identifier
      state.order.paymentAccountIdentifier = action.payload;
    },
    /**
     * Set the currency for the order
     *
     * @param state - Current state
     * @param action - Payload with currency
     */
    addOrderCurrency(state, action: PayloadAction<string>) {
      if (!state.order) {
        // If no order exists, do nothing
        return;
      }
      // Set the currency
      state.currency = action.payload;
    },
  },
});

// Exporting actions generated by createSlice
export const {
  remove: removeOrder, // Action to remove an order
  create: createOrder, // Action to create an order
  addData, // Action to add or update form data
  addProducts, // Action to add products
  addPaymentMethods, // Action to add payment methods
  addPaymentMethod, // Action to set payment account identifier
  addOrderCurrency, // Action to set currency
} = orderReducer.actions;

// Exporting the reducer generated by createSlice
export default orderReducer.reducer;
