// Importing necessary types and functions from Redux Toolkit
import type { PayloadAction } from '@reduxjs/toolkit';
import { createSlice } from '@reduxjs/toolkit';
// Importing interfaces for order product data and order form data
import type {
  IOrderProductData,
  IOrdersFormData,
} from 'oneentry/dist/orders/ordersInterfaces';

// Defining the application-specific order type
export type IAppOrder = {
  formIdentifier?: string; // Optional identifier for the form
  paymentAccountIdentifier?: string; // Optional identifier for the payment account
  formData: Array<IOrdersFormData & { valid?: boolean }>; // Array of form data with an optional validity flag
  products: Array<IOrderProductData>; // Array of order product data
};

/**
 * Defining the shape of the initial state for the order slice.
 *
 * @property {IAppOrder} order - The current order.
 * @property {string | undefined} currency - Optional currency type for the order.
 * @property {Array<{ identifier: string }> | undefined} paymentMethods - Optional array of payment methods.
 */
type InitialStateType = {
  order: IAppOrder;
  currency?: string;
  paymentMethods?: Array<{
    identifier: string;
  }>;
};

/**
 * Initial state for the order slice.
 *
 * @property {IAppOrder} order - The current order.
 * @property {Array} order.formData - Array of form data.
 * @property {Array} order.products - Array of products.
 */
const initialState: InitialStateType = {
  order: {
    formData: [],
    products: [],
  },
};

/**
 * Creating a Redux slice for order management.
 */
const orderReducer = createSlice({
  initialState,
  name: 'order',
  reducers: {
    /**
     * Create or update an order.
     *
     * @param state - Current state.
     * @param action - Payload with order data.
     */
    create(state, action: PayloadAction<IAppOrder>) {
      if (!state.order) {
        // If no order exists, set the new order
        state.order = action.payload;
      } else {
        // Merge the new order data with the existing order
        state.order = {
          ...action.payload,
          ...state.order,
        };
      }
    },
    /**
     * Remove an order by resetting it to its initial state.
     *
     * @param state - Current state.
     */
    remove(state) {
      state.order = {
        formData: [], // Reset form data
        products: [], // Reset products
      };
    },
    /**
     * Add or update form data in the order.
     *
     * @param state - Current state.
     * @param action - Payload with form data.
     */
    addData(
      state,
      action: PayloadAction<IOrdersFormData & { valid?: boolean }>,
    ) {
      if (!state.order) {
        return; // If no order exists, do nothing
      }
      const ind = state.order.formData.findIndex(
        (item) => item.marker === action.payload.marker,
      );

      if (ind !== -1) {
        state.order.formData[ind] = action.payload; // Update existing form data
      } else {
        state.order.formData.push(action.payload); // Add new form data
      }
    },
    /**
     * Add products to the order
     *
     * @param state - Current state
     * @param action - Payload with array of products
     */
    addProducts(state, action: PayloadAction<IOrderProductData[]>) {
      if (!state.order) {
        return; // If no order exists, do nothing
      }
      state.order.products = action.payload; // Set the products in the order
    },
    /**
     * Add payment methods to the order
     *
     * @param state - Current state
     * @param action - Payload with array of payment methods
     */
    addPaymentMethods(
      state,
      action: PayloadAction<
        Array<{
          identifier: string;
        }>
      >,
    ) {
      if (!state.paymentMethods) {
        state.paymentMethods = action.payload; // Set the payment methods if they don't exist
      }
    },
    /**
     * Set the payment account identifier for the order
     *
     * @param state - Current state
     * @param action - Payload with payment method identifier
     */
    addPaymentMethod(state, action: PayloadAction<string>) {
      if (!state.order) {
        return; // If no order exists, do nothing
      }
      state.order.paymentAccountIdentifier = action.payload; // Set the payment account identifier
    },
    /**
     * Set the currency for the order
     *
     * @param state - Current state
     * @param action - Payload with currency
     */
    addOrderCurrency(state, action: PayloadAction<string>) {
      if (!state.order) {
        return; // If no order exists, do nothing
      }
      state.currency = action.payload; // Set the currency
    },
  },
});

// Exporting actions generated by createSlice
export const {
  remove: removeOrder, // Action to remove an order
  create: createOrder, // Action to create an order
  addData, // Action to add or update form data
  addProducts, // Action to add products
  addPaymentMethods, // Action to add payment methods
  addPaymentMethod, // Action to set payment account identifier
  addOrderCurrency, // Action to set currency
} = orderReducer.actions;

// Exporting the reducer generated by createSlice
export default orderReducer.reducer;
